update public.case_studies
set
  tagline = 'Flex Onboarding — Compliance Workflow Design',

  metrics = '[
    {"value":"76%","label":"of Flex clients lacked a compliant I-9 workflow","context":"the compliance gap this project was designed to close"},
    {"value":"26","label":"Rounds of design exploration and testing","context":"across 18 participants across employee and admin journeys"},
    {"value":"2,548","label":"Survey responses post first release","context":"confirmed the integrated direction was working"}
  ]'::jsonb,

  reflections = '[
    {"title":"What worked.","body":"Anchoring a compliance-heavy workflow to familiar onboarding patterns made I-9 feel native to the product rather than a bolted-on task. A single usability test with 7 users was enough to shift a product decision and protect a better experience — data beats opinion. Combining iterative testing with clear handoff strategy created a stronger foundation for both usability and business growth."},
    {"title":"What I''d do differently.","body":"Establish third-party alignment earlier — waiting on compliance validation from HIREtech created rework and slowed design iterations. Moving faster through compliance content decisions by setting clearer approval checkpoints upfront, rather than iterating in circles, would have saved time."},
    {"title":"What this unlocked.","body":"The project exposed a missing pattern in Flex for communicating third-party transitions to users. Solving it here created a reusable transparency pattern that addressed a systemic problem affecting multiple integrations across the platform."}
  ]'::jsonb,

  content_blocks = $json$[
    {"id":"overview","type":"overview","title":"Project Overview","body":"The I-9 and E-Verify initiative focused on helping Flex clients manage employment verification and onboarding compliance more efficiently within the platform. The experience enabled new hires to complete Section 1 of Form I-9 and allowed administrators to complete Section 2 through an integration with HIREtech, a third-party vendor. The solution also supported Remote I-9 requests, onboarding task visibility, document access, and transaction-based billing tied directly to onboarding."},
    {"id":"situation","type":"custom","title":"Situation","body":"76% of Flex clients had no compliant I-9 and E-Verify workflow during onboarding.\n\nManual workarounds created compliance risk and operational friction across hiring workflows."},
    {"id":"task","type":"custom","title":"Task","body":"","payload":{"items":["Owned the end-to-end UX process as sole designer, from research to final handoff.","Designed for both the employee journey (Section 1) and the admin journey (Section 2 and status tracking).","Integrated I-9 and E-Verify into Flex without fragmenting the existing onboarding experience."]}},
    {"id":"research","type":"custom","title":"Research & Discovery","body":"","payload":{"items":["Stakeholder interviews with 2 BAs, 3 engineers, 2 product leads, and ~30 HR clients confirmed the approach: integrate I-9 into the existing onboarding flow using familiar components and patterns rather than building a separate experience.","Hotjar analysis of existing onboarding flow recordings revealed users dropped off due to heavy content and unclear guidance, creating friction before the handoff even occurred.","Maze and moderated usability testing across 18 participants and 26 rounds showed the biggest clarity gap was at the HIREtech handoff — users hesitated without stronger ownership cues and redirect context.","A post-release survey with 2,548 responses validated the integrated direction was working and surfaced specific areas needing refinement after launch."]}},
    {"id":"actions","type":"custom","title":"Actions","body":"","payload":{"items":["Conducted 26 rounds of design exploration and usability testing using Maze and moderated sessions across 18 participants to validate task ownership, redirect clarity, and status visibility.","Pushed back on product's decision to place I-9 settings in the hiring dashboard — ran a usability test where 7 out of 7 users navigated to Settings naturally, and used that data to realign the team.","Aligned the I-9 workflow with familiar onboarding patterns like W-4 and direct deposit, defining clearer handoff moments, progress states, and completion feedback between Flex and HIREtech.","Built an interactive prototype covering the full employee and admin flows, including task initiation, redirect, status visibility, and completion states.","Delivered detailed design specs for development including behaviors, content examples, component definitions, and edge case documentation.","Designed email communications to announce the new integration and follow up with users who did not complete the I-9 process.","Created handoff guidelines documenting how the Flex to HIREtech integration was communicated to users, covering redirect messaging, progress states, and completion feedback."]}},
    {"id":"impact","type":"results","title":"Result","body":"","payload":{"rows":[{"metric":"Task completion rate","value":"+12%"},{"metric":"Avg time on task","value":"−26%"},{"metric":"Redirect hesitation","value":"−13%"},{"metric":"Status interpretation errors","value":"−9%"},{"metric":"User confidence score","value":"+0.8"}],"insights":["Task completion rate — 69% (early concept) to 81% (refined concept).","Average time on task — 4m 12s to 3m 06s.","Redirect hesitation reduced from 46% to 33%.","Status interpretation errors down from 31% to 22%.","User confidence score improved from 3.2/5 to 4.0/5.","Manual process dependency baseline established at 60–70%; target set at under 25% for post-launch tracking.","2,548 survey responses post first release confirmed the integrated direction was working."]}}
  ]$json$::jsonb

where slug = 'i9-everify-integration';
