update public.case_studies
set
  tagline = 'Led an accessibility audit and system unification effort to reduce pattern debt, improve consistency, and strengthen design-to-development delivery across Flock.',
  metrics = '[{"value":"6 mo","label":"Audit and prioritization","context":"initial accessibility and system review"},{"value":"1 system","label":"Shared foundation","context":"aligned patterns, typography, icons, and dialogs"},{"value":"2 designers","label":"Working with 3 developers","context":"cross-functional system effort"}]'::jsonb,
  my_role = array['Accessibility Audit Lead','Component Strategy','Design Systems','Engineering Partnership'],
  problem = '{"admin_pain_points":["The product had accessibility risk across core flows and no mature shared library to address issues systematically.","Teams were working with duplicated patterns, inconsistent naming, and fragmented component behavior across pages.","Weak documentation and handoff ambiguity created implementation friction and made system decisions harder to scale."],"user_pain_points":["Inconsistent components made the experience less predictable from page to page.","Accessibility gaps reduced clarity and usability for people relying on stronger hierarchy, focus treatment, and consistent interaction states.","Dialogs, icons, typography, and responsive behavior lacked enough shared rules to feel cohesive across the product."]}'::jsonb,
  constraints = array['Accessibility improvements had to happen while the product was live and already fragmented across multiple pages and patterns.','There was no fully mature design system in place, so audit work and system definition had to progress together.','The system needed to support real engineering constraints, QA, and implementation readiness rather than remain a Figma-only cleanup effort.'],
  methodology = '{"name":"Audit to Systemization","steps":[{"step":1,"label":"Audit","description":"Reviewed accessibility issues, page-level inconsistencies, and component debt across the product."},{"step":2,"label":"Prioritize","description":"Grouped findings by severity, implementation risk, and system impact to clarify what needed structural change first."},{"step":3,"label":"Define","description":"Separated accessibility fixes from design-system decisions by documenting patterns, variants, states, and usage rules."},{"step":4,"label":"Align","description":"Worked closely with developers to adapt component decisions to implementation realities, QA needs, and handoff clarity."},{"step":5,"label":"Validate","description":"Used design review, accessibility checks, and implementation feedback to strengthen adoption and consistency over time."}]}'::jsonb,
  design_strategy = array['Use accessibility auditing as a structural input to system design rather than treating compliance as a late-stage QA task.','Clarify foundations, components, patterns, and modules so teams know when to use each pattern and how it should behave.','Reduce ambiguity for engineering by defining states, variants, responsive behavior, and documentation that supports implementation.'],
  reflections = '[{"title":"Leadership needs criteria.","body":"This work became stronger once success criteria were explicit. The team needed clear signals for what should be fixed first, what should become reusable, and what good implementation looked like."},{"title":"Systems work is product work.","body":"The most valuable outcome was not a prettier library. It was a clearer product foundation that reduced ambiguity, improved accessibility decisions, and helped design and engineering move with more confidence."}]'::jsonb,
  content_blocks = $json$[
    {"id":"overview","type":"overview","title":"Overview","body":"Flock had accumulated accessibility risk, duplicated interface patterns, and inconsistent component behavior across the product. I led an audit and system-unification effort to clarify what was broken, prioritize what mattered most, and create a stronger shared foundation for both product quality and implementation."},
    {"id":"team-context","type":"custom","title":"Team","body":"I led the audit framing, defined which patterns needed consolidation, and partnered with engineering on how components should behave in build. I worked alongside another designer, in collaboration with a UX Lead, UX Manager, Product Owner, Business Analyst, three developers, and a Dev Lead."},
    {"id":"situation","type":"custom","title":"Situation","body":"Flock had accumulated accessibility risk, duplicated interface patterns, and inconsistent component behavior across its product surfaces.\n\nThe lack of a mature system meant icons, typography, dialogs, and reusable UI patterns had drifted over time. That created friction for implementation, made handoff less reliable, and increased the cost of keeping the experience consistent.\n\nThis mattered beyond visual polish. It affected accessibility readiness, product quality, and the team's ability to scale improvements without re-solving the same problems page by page."},
    {"id":"task","type":"custom","title":"Task","body":"My role was to turn accessibility findings and UI inconsistencies into a clearer system direction.\n\nThat meant identifying what was broken, separating audit issues from system decisions, and helping define reusable patterns that design and engineering could actually adopt.\n\nSuccess meant reducing duplicated patterns, improving consistency between pages, clarifying handoff expectations, and creating stronger accessibility guidance for future work."},
    {"id":"research","type":"custom","title":"Audit Findings","payload":{"items":["Duplicate components existed with conflicting spacing, hierarchy, and interaction behavior.","Icons and typography lacked enough shared guidance for naming, usage, and accessibility consistency.","Dialogs and other high-impact surfaces showed inconsistent structure, dismissal patterns, and focus expectations.","States and variants were not documented clearly enough, which made implementation and QA more ambiguous.","Responsive behavior was not defined consistently, so layouts and components drifted between contexts.","Handoff materials lacked enough do / don't guidance, accessibility notes, and implementation-ready rules."]}},
    {"id":"actions","type":"custom","title":"Actions","payload":{"items":["Built an audit framework that grouped issues by severity, system impact, and implementation complexity instead of treating findings as isolated UI bugs.","Separated the work into accessibility findings, design-system inconsistencies, and engineering constraints so each stream could be addressed with the right decision-making lens.","Reviewed foundations and reusable patterns across icons, typography, dialogs, and shared components to identify where states, variants, and naming needed to be standardized.","Defined clearer reusable patterns with documented states, composition rules, and responsive expectations so the system could scale beyond one-off page fixes.","Added stronger guidance in Figma through examples, usage notes, and documentation that made handoff clearer for engineering and reduced ambiguity in implementation.","Partnered closely with developers during review and QA to adjust patterns to real technical constraints and validate that the proposed system decisions held up in build."]}},
    {"id":"impact","type":"results","title":"Product/System Outcomes","body":"The project created a clearer system foundation for accessibility, component reuse, and implementation consistency. Because confirmed business metrics were not preserved, the outcomes are framed through product, system, and delivery signals.","payload":{"rows":[{"metric":"Accessibility risk","value":"Lowered"},{"metric":"Pattern debt","value":"Reduced"},{"metric":"Handoff clarity","value":"Stronger"}],"insights":["The audit made severity and prioritization visible, which helped the team address structural accessibility problems instead of isolated UI fixes.","Shared guidance for icons, typography, dialogs, and reusable patterns reduced inconsistency and gave the system a clearer source of truth.","Defining states, variants, and usage rules reduced ambiguity between design and engineering and improved the quality of implementation conversations."],"projected":["Fewer duplicated patterns and less visual inconsistency across updated pages.","A clearer adoption path for reusable components, patterns, and modules.","More reliable handoff and QA because accessibility notes and usage guidance are documented.","Lower risk in future accessibility reviews by addressing issues systemically instead of page by page."],"successMetrics":["Reduction of duplicated or conflicting component patterns.","Improved consistency of states, variants, and responsive behavior across reused modules.","Fewer implementation questions during handoff and QA.","Accessibility issues identified and resolved by severity before release.","Adoption of standardized patterns in new or updated product areas."]}}
  ]$json$::jsonb
where slug = 'flock-accessibility-system';
